### ISSUE TITLE
Possible to not require List::Util 1.55?

### ISSUE THREAD

**Issue by matthewdarwin** [karenetheridge/JSON-Schema-Draft201909#34]
Is it possible to not require List::Util 1.55?

List::Util 1.55 is pretty new.  My platform (debian 10) comes with List::Util 1.50.

Trying to build and then override the core List::Util seems a bit problematic

```
$ dh-make-perl --core-ok --build --cpan List::Util
[omit output]
$ dpkg --install libscalar-list-utils-perl_1.55-1_amd64.deb
(Reading database ... 50436 files and directories currently installed.)
Preparing to unpack libscalar-list-utils-perl_1.55-1_amd64.deb ...
Unpacking libscalar-list-utils-perl (1.55-1) over (1.55-1) ...
dpkg: dependency problems prevent configuration of libscalar-list-utils-perl:
 perl-base (5.28.1-6+deb10u1) breaks libscalar-list-utils-perl (<< 1:1.50) and is installed.
  Version of libscalar-list-utils-perl to be configured is 1.55-1.

dpkg: error processing package libscalar-list-utils-perl (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 libscalar-list-utils-perl
```

**Comment by karenetheridge** [comment]
Hey, it's neat to see someone else using this (even though it's not quite done yet).

Version 1.55 is needed for `uniqint`. But if you're using debian's package installer, they should have used the proper dependencies, and built a newer List::Util if this package required it. Have you filed a ticket with debian?

**Comment by matthewdarwin** [comment]
List::Util is part of the core perl package in debian. I'm sure the update will be in debian 11.  But that's probably like 1+ years in the future.

Just thought I would ask.

**Comment by karenetheridge** [comment]
Ok, I was confused how you could be installing this module on debian when the prerequisites weren't satisfied.  If you are installing via a different mechanism, prerequisites will be satisfied differently - you can't expect debian to provide them.  If you use a cpan client, it will install all the prerequisites for you; if you install manually (e.g. download the tarball and follow the INSTALL instructions) you will have to resolve them yourself.
